// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzG2i-pDhJNpDqcImBVN3dAv_yTiQ04S4',
    appId: '1:116482239911:web:c78dfd05f1c8e218035a82',
    messagingSenderId: '116482239911',
    projectId: 'alzheimerapp-6c843',
    authDomain: 'alzheimerapp-6c843.firebaseapp.com',
    storageBucket: 'alzheimerapp-6c843.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABprDPwSBd2JwMKHVUZ97tQ-LlCfu9ZgY',
    appId: '1:116482239911:android:018a62a5daad59cf035a82',
    messagingSenderId: '116482239911',
    projectId: 'alzheimerapp-6c843',
    storageBucket: 'alzheimerapp-6c843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABhTd6iQpNiKT-ymzM-_egoooREMbIYYY',
    appId: '1:116482239911:ios:4d93ba5f1d91b000035a82',
    messagingSenderId: '116482239911',
    projectId: 'alzheimerapp-6c843',
    storageBucket: 'alzheimerapp-6c843.appspot.com',
    iosBundleId: 'com.example.licenta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABhTd6iQpNiKT-ymzM-_egoooREMbIYYY',
    appId: '1:116482239911:ios:14cedea6a3e342d2035a82',
    messagingSenderId: '116482239911',
    projectId: 'alzheimerapp-6c843',
    storageBucket: 'alzheimerapp-6c843.appspot.com',
    iosBundleId: 'com.example.licenta.RunnerTests',
  );
}
